# Generated by Django 5.0.7 on 2024-07-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-created_at",)},
        ),
    ]
