# Generated by Django 5.0.7 on 2024-07-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done", "-created_at"]},
        ),
    ]
